pub const ALGORITHM_SOURCE_DIR: &str = "./algorithm-runner";
pub const TMP_BUILD_DIR: &str = "/tmp/algorithm-runner";
pub const TMP_ALGORITHM_RS: &str = "/tmp/algorithm-runner/src/algorithm/algorithm.rs";
pub const TMP_METADATA_RS: &str = "/tmp/algorithm-runner/src/algorithm/metadata.rs";
pub const CHECKED_FILE_PATH: &str = "src/strategy/strategy.rs";
pub const BUILT_WASM: &str =
    "/tmp/algorithm-runner/target/wasm32-wasip1/release/algorithm_runner.wasm";
pub const BUILT_CWASM: &str = "/tmp/algorithm-runner/algorithm-runner.cwasm";
pub const COMPILER_MESSAGE: &str = "compiler-message";
pub const BUILD_FINISHED: &str = "build-finished";
pub const S3_BUCKET_UPLOADS: &str = "stock-trek-uploads";
pub const DEFAULT_LOCK_TABLE: &str = "algorithm-compiler-locks";
pub const REPO_CACHE_DIR: &str = "/tmp/repos";
pub const REPO_ARCHIVE_DIR: &str = "/tmp/repo-archives";
pub const LOCK_RETRIES: u32 = 60;
pub const LOCK_RETRY_DELAY_MS: u64 = 1000;
pub const LEVEL_ERROR: &str = "error";
pub const RESULT_SUCCESS: &str = "SUCCESS";
pub const RESULT_FAILURE: &str = "FAILURE";
